apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fortify-ingressroute
  namespace: fortify
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`fortify-ai.kikoichi.dev`) && PathPrefix(`/api`)
      kind: Rule
      priority: 1000
      services:
        - name: api-gateway
          port: 3001
          nativeLB: true
    - match: Host(`fortify-ai.kikoichi.dev`) && PathPrefix(`/`)
      kind: Rule
      priority: 900
      services:
        - name: frontend
          port: 3000
          nativeLB: true
    - match: PathPrefix(`/api`)
      kind: Rule
      priority: 800
      services:
        - name: api-gateway
          port: 3001
          nativeLB: true
    - match: PathPrefix(`/`)
      kind: Rule
      priority: 700
      services:
        - name: frontend
          port: 3000
          nativeLB: true
