apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fortify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/iamzidar/fortify-ai/frontend:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: production
            - name: API_GATEWAY_URL
              value: "http://api-gateway:3001"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
