apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fcli-state-pvc
  namespace: fortify
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
